version: "3.7"
services:
    nodeserver:
        build:
            context: ./expressjs
        ports:
            - "5000:5000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"